### PR TITLE
Reworked icons

### PR DESCRIPTION
**Pull request by DaveSch-gramps**
Reworked icons without using png files.

I hope these meet everyone's expectations.

### CODE REVIEW

**Comment by DaveSch-gramps** [comment]
The quickest merge request ever. Both clearing our desks for the weekend, but one of us working late.

**Comment by cdhorn** [comment]
I greatly appreciate the hand, graphic arts type stuff is not something I'm very good at. So thanks again!

**Comment by emyoulation** [comment]
Thanks Dave!

They appear crisp (foreground and background) now.  Nice work!

**Comment by PQYPLZXHGF** [comment]
@DaveSch-gramps  Great stuff, thank you.

@cdhorn The readme shows the original Linkedview icon should it be removed or replaced by one of these; or a new one be made?

**Comment by cdhorn** [comment]
Oh I suppose that and the screenshots ought to get replaced at some point.

**Pull request merged**
