### PR TITLE
Change view names to include Card

### PR DESCRIPTION
**Pull request by DaveSch-gramps**
Think it is self explained

### CODE REVIEW

**Comment by emyoulation** [comment]
I strongly recommend that CardView be used not "Card" or "Card View" (with a space).

CardView is unique & searchable. "Card" is too generic, "view" getting thousands of matches on our wiki.

**Comment by DaveSch-gramps** [comment]
What about "Person-Card" ?? Would that be searchable?

**Comment by emyoulation** [comment]
It would be unique enough, yes. But... If you used CardView in the mode name across all the Categories, then you get a search that offers a full spectrum of search capabilities "Person CardView" finds a single. "CardView" find the People & Relationships (and the other categories too)

Have you tried to search for all the CardView .ini files when you upgrade? (They need to be cleaned out regularly during beta.) No Windoze search finds all the mode, bottombar & sidebar .ini files. (Plus, there is 1 for each database & for each template.) It is a MESS.

CardView needs its own subdirectory.

**Comment by cdhorn** [comment]
Thanks Dave!  With the discussion here I am going to hold off on a merge for a short bit in case any other ideas pop up.

Personally I am fine with Person Card, Family Card, etc... that seems clean to me.

All the other view titles that are more than one word have a space between words, so I don't think CardView really "fits".

I think "Person Card View" could work but it is pretty long, thinking about Toolbar Text mode on. 

Also thinking ahead if Nick splits the CombinedView in a similar manner I'm not sure how he would want to name that.  Those might perhaps become the base "Person", "Family" etc that I currently use, or "Person View", "Family View" etc...

**Comment by fxtmtrsine** [comment]
@DaveSch-gramps Thank you for the updated icons 🥇

**Pull request merged**
